### ISSUE TITLE
为何不提交到 Specs?

### ISSUE THREAD

**Issue by VincentSit** [jcccn/ShareSDK-iOS#2]

**Comment by jcccn** [comment]
因为不是官方的Spec。所以没有提交到master Specs。
但是提交到了我一个私有的Specs：
https://github.com/jcccn/PodSpecs

**Comment by VincentSit** [comment]
我认为不用管官方的问题，这几年我催了不止一次了，到现在都不支持。

建议还是提交一下方便大家搜索使用。

**Comment by jcccn** [comment]
嗯，我先跟ShareSDK打声招呼，近期提交吧。
你先将就用着吧。

**Comment by jcccn** [comment]
@VincentSit 有人已经提交到官方了。
看 [MobShareSDK](https://github.com/shingwasix/MobShareSDK)
